// prettier-ignore
require('dotenv').config({
    path: `.env`,
});
const colors = require('tailwindcss/colors');
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    future: {
        // removeDeprecatedGapUtilities: true,
        // purgeLayersByDefault: true,
    },
    purge: {
        enabled: process.env.PURGE_TAILWIND === "true",
        content: [
            './src/**/*.js',
            './src/**/*.jsx',
            './src/**/*.ts',
            './src/**/*.tsx',
        ],
    },
    theme: {
        screens: {
            'xs': '475px',
            ...defaultTheme.screens,
        },
        extend: {
            gridTemplateColumns: {
                '16': 'repeat(16, minmax(0, 1fr))',
            },
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
                gray: colors.blueGray,
                teal: colors.teal,
                red: colors.red,
                rose: colors.rose,
                emerald: colors.emerald,
                teal: colors.teal,
                blue: colors.blue,
            },
            spacing: {
                '1/4': '0.0625rem',
                '1/2': '0.125rem',
                '3/4': '0.1875rem',
                '3/2': '0.375rem',
                  '5vh':   '5vh',
                 '10vh':  '10vh',
                 '15vh':  '15vh',
                 '20vh':  '20vh',
                 '25vh':  '25vh',
                 '30vh':  '30vh',
                 '35vh':  '35vh',
                 '40vh':  '40vh',
                 '45vh':  '45vh',
                 '50vh':  '50vh',
                 '60vh':  '60vh',
                 '70vh':  '70vh',
                 '80vh':  '80vh',
                 '90vh':  '90vh',
                '100vh': '100vh',
                  '5vw':   '5vw',
                 '10vw':  '10vw',
                 '15vw':  '15vw',
                 '20vw':  '20vw',
                 '25vw':  '25vw',
                 '30vw':  '30vw',
                 '35vw':  '35vw',
                 '40vw':  '40vw',
                 '45vw':  '45vw',
                 '50vw':  '50vw',
                 '55vw':  '55vw',
                 '60vw':  '60vw',
                 '65vw':  '65vw',
                 '70vw':  '70vw',
                 '75vw':  '75vw',
                 '80vw':  '80vw',
                 '85vw':  '85vw',
                 '90vw':  '90vw',
                 '95vw':  '95vw',
                '100vw': '100vw',

                 '12':  '3.0rem',
                 '14':  '3.5rem',
                 '16':  '4.0rem',
                 '18':  '4.5rem',
                 '20':  '5.0rem',
                 '21':  '5.25rem',
                 '22':  '5.5rem',
                 '24':  '6.0rem',
                 '56': '14.0rem',
                 '58': '14.5rem',
                 '60': '15.0rem',
                 '62': '15.5rem',
                 '64': '16.0rem',
                 '66': '16.5rem',
                 '68': '17.0rem',
                 '70': '17.5rem',
                 '72': '18.0rem',

                '124': '31.0rem',
                '126': '31.5rem',
                '128': '32.0rem',
                '130': '32.5rem',
                '132': '33.0rem',
                '192': '48.0rem',
                '256': '64.0rem',
            },
        },
    },
    plugins: [],
};